### ISSUE TITLE
react css howto 

### ISSUE THREAD

**Issue by happypeter** [happypeter/react-meteor-book#10]
> 再谈谈开发风格的偏好：React 推荐的做法是 JSX + inline style，也就是把 HTML 和 CSS 全都整进 JavaScript 了。Vue 的默认 API 是以简单易上手为目标，但是进阶之后推荐的是使用 webpack + vue-loader 的单文件组件格式：

http://www.zhihu.com/question/31585377/answer/52576501?utm_source=weibo&utm_medium=weibo_share&utm_content=share_answer&utm_campaign=share_button

**Comment by happypeter** [comment]
https://speakerdeck.com/vjeux/react-css-in-js

这个里面的观点对我来说没有价值。首先，只有大 scale 的代码，就像作者自己说的才有他说的这七个问题，实话说，在我自己写的小项目中，这些根本就不成为痛点。

当然，如果代价很小，那么提前预防一下也是明智的，但是恰恰相反，用 js 操作 css 的思路虽然灵活，但是使用起来极其不方便，‘backGround`，`m()` ... 太多的麻烦了。

所以，暂时不用！@billie66

**Comment by billie66** [comment]
ok

**Comment by happypeter** [comment]
Pete 的 rethink best practice 演讲中，介绍了放弃 handlebar 以及 angular 的各种愚蠢的新概念的主张，说 js 原生的结构用来操作 html 就能实现更为丰富和灵活的效果了，这个我是100%接受的，确实很帅。

所以推广到 css 这边，用 js 直接操作 style 是不是也更灵活的，我觉得也会的，但是上面演讲中的内容不是我想要的东西，期待其他的思路。

**Comment by happypeter** [comment]
http://christianalfoni.github.io/react-webpack-cookbook/Loading-CSS.html

这里的加载 css 的方案倒是很干净利落，但是也没觉得有任何的必要性，直接用 sass 打包成一个 all.css 加载不是一样吗？

**Comment by happypeter** [comment]
方案定下了，就用  sass 自己的那一套。
