### ISSUE TITLE
react + meteor 配合使用

### ISSUE THREAD

**Issue by billie66** [happypeter/react-meteor-book#14]
reply 现在大家都说很复杂，有很多企业级的考量，所以用 meteor 做后端

**Comment by luckyyang** [comment]
meteor写代码效率还是非常高的，这月底的1.2版本会支持 react 和 es6。现在其实已经有package 和教程了。

PS：meteor 在 github 上 star 的数量已经超过了 rails

**Comment by luckyyang** [comment]
https://github.com/search?o=desc&q=stars%3A%3E1&ref=searchresults&s=stars&type=Repositories&utf8=%E2%9C%93

**Comment by happypeter** [comment]
🐂

**Comment by happypeter** [comment]
🐮

**Comment by kannans** [comment]
:+1:

**Comment by billie66** [comment]
``` bash
curl https://install.meteor.com/ | sh

```

meteor 龟速安装中

在 imac 10.6.8 中安装成功，也能顺利地运行起来，真是挺简单的

**Comment by billie66** [comment]
``` bash
meteor create --example todos
cd todos
meteor run
```

通过上面几条命令就能把 meteor 的 todos 例子运行起来了，界面很美而且是响应式的

**Comment by billie66** [comment]
good meteor tutorial serials

https://www.youtube.com/watch?v=hgjyr6BPAtA&list=PLLnpHn493BHECNl9I8gwos-hEfFrer7TV

**Comment by billie66** [comment]
从命令行中启动 mongodb 

``` bash
meteor mongo
```

**Comment by luckyyang** [comment]
https://github.com/maodouio/meteor-lean-startup-camp/blob/master/learning_materials.md

**Comment by billie66** [comment]
@luckyyang 多谢

your second meteor tutorial:

http://meteortips.com/second-meteor-tutorial/

**Comment by happypeter** [comment]
@billie66 来实现一个简单的 demo 吧。

我觉得有两种可行方案：
- 一种是 server rendering ，这一种跟传统用 rails 的感觉类似
- 另一种是 react 自己在前端，有自己的 react-router ，也就是一个 spa ，然后 meteor 做 api 服务器这种。

不过，我觉得 metor 官方给出的方案肯定是最合适的，咱们先安找它那个走。

**Comment by billie66** [comment]
http://alexgaribay.com/2015/07/06/getting-started-with-meteor-react-and-react-router/

**Comment by billie66** [comment]
sublime 配置

http://info.meteor.com/blog/set-up-sublime-text-for-meteor-es6-es2015-and-jsx-syntax-and-linting

官方文档

http://react-in-meteor.readthedocs.org/en/latest/

meteor + react tutorial 

http://tutorial-viewer.meteor.com/tutorial/0/react

**Comment by billie66** [comment]
一篇介绍 react 和 meteor 的文章 http://www.sitepoint.com/3-javascript-libraries-keep-eye-2015/

**Comment by billie66** [comment]
https://forums.meteor.com/t/tell-me-whats-it-like-to-use-react-with-meteor/3921

http://www.alvareznavarro.es/blog/2015/6/developing-an-application-with-meteor-and-react

**Comment by billie66** [comment]
@happypeter  已经总结到 wiki 了,  [meteor 和 react 配合使用](https://github.com/happypeter/react-book/wiki/meteor-%E5%92%8C-react-%E9%85%8D%E5%90%88%E4%BD%BF%E7%94%A8)

**Comment by happypeter** [comment]
react  创始团队中的谁加入了 meteor ？

**Comment by billie66** [comment]
下面项目的主要贡献者 https://github.com/benjamn 是 facebook 的员工，不知道是不是 react 创始团队的成员

https://github.com/reactjs/react-meteor

**Comment by billie66** [comment]
benjamn 也是 react 主要贡献者 https://github.com/facebook/react/graphs/contributors

**Comment by luckyyang** [comment]
7月份的 meteor devshop 他也讲了点东西：
https://youtu.be/aa3C9FilfPg?t=2833

他前面讲得是 meteor 的 ceo

**Comment by happypeter** [comment]
鉴于大家对 flux relay 的各种抱怨，我现在感觉用 meteor 来配合 react 似乎真是上策。

**Comment by billie66** [comment]
看了官方的 react-todos 代码之后，觉得 meteor 和 react 之间数据交互真是很方便
