### ISSUE TITLE
meteor 读文件，发 json api

### ISSUE THREAD

**Issue by billie66** [happypeter/react-meteor-book#16]

**Comment by billie66** [comment]
http://stackoverflow.com/questions/15374066/importing-a-json-file-in-meteor

**Comment by billie66** [comment]
http://info.meteor.com/blog/optimistic-ui-with-meteor-latency-compensation

**Comment by billie66** [comment]
meteor 应用中读取本地静态文件，下面链接中提到了三种方法

http://stackoverflow.com/questions/15374066/importing-a-json-file-in-meteor 

其中第一种方法会用到数据库，因为不想使用数据库，所以先排除。

第二种方法，需要安装 http package，在本地没有测试成功，无法得到要读取文件的路径，相关知识还不熟悉，所以放弃

第三种方法，需要用到 meteor 自带的 Assets 接口，本地测试成功。不过需要注意几点：
- 出于安全方面的考虑，静态文件的存放位置是有限制的，需要放置在项目根目录下的 private 目录中，这样 Assets.getText() 接口才能访问到文件，例如读取 private 目录下子目录 md 中的 cat 文件：

``` js
Assets.getText('md/cat')
```
- 另一个就是关于路由的问题，首先安装目前最流行的 iron:router 包

```
meteor add  iron:router
```

然后创建一个 router.js 文件，官方 todos 实例中把这个文件放到项目根目录下的 lib 目录中，router.js 的代码如下：

``` js
Router.route('/file/:filename', function () {
  var name = this.params.filename;
  var file = Assets.getText('md/' + name);
  var result = {content: file};
  this.response.end(JSON.stringify(result));
}, {where: 'server'});
```

代码中的 filename 是一个动态参数，可以在 url 中指定不同的文件名，从而得到不同的内容
- 不需要创建名字为 file 的模板文件，因为只提供的 json api，看一下项目的目录结构吧

![screen shot 2015-08-23 at 9 32 41 pm](https://cloud.githubusercontent.com/assets/102444/9428370/8e895704-49de-11e5-8528-b80f342ef988.png)

非常简单，就两个目录 lib 和 private，所有任务都交给 router 处理了。
- 得到 json 数据，在命令行输入下面的命令：

``` bash
curl -i -H "Accept: application/json" "http://localhost:3000/file/cat"

HTTP/1.1 200 OK
vary: Accept-Encoding
date: Sun, 23 Aug 2015 13:51:07 GMT
connection: keep-alive
transfer-encoding: chunked

{"content":"hello cat\nhello cat\nhello cat\n"}%
```

**Comment by happypeter** [comment]
总结到 wiki 了。
