### ISSUE TITLE
meteor 实现基本的用户认证系统

### ISSUE THREAD

**Issue by billie66** [happypeter/react-meteor-book#18]
参考 http://meteortips.com/second-meteor-tutorial/user-accounts/

**Comment by billie66** [comment]
实现过程已经总结到 wiki 

[Meteor 用户认证系统](https://github.com/happypeter/react-book/wiki/Meteor-%E7%94%A8%E6%88%B7%E8%AE%A4%E8%AF%81%E7%B3%BB%E7%BB%9F)

**Comment by happypeter** [comment]
wikied
