### ISSUE TITLE
链接中去掉 #

### ISSUE THREAD

**Issue by happypeter** [happypeter/react-meteor-book#2]
我有一个思路：

可以输入 e.com/login 用 js 把 "login" 取到，然后根据这个字符串决定去用哪个 jsx 就行了，这样就用不到 pushstate 接口了。

**Comment by billie66** [comment]
这个问题讨论 http://stackoverflow.com/questions/25086832/how-to-stop-in-browser-with-react-router

使用下面的代码是可以去掉地址中的 /#/ 符号，测试浏览器 chrome

```
Router.run(routes, Router.HistoryLocation, function (Handler) {
  React.render(<Handler/>, document.body);
});
```

**Comment by billie66** [comment]
在本地测试的时候，如果使用 `Router.HistoryLocation` ，刷新页面会报出 404 错误。比如说页面中有一个链接，点击链接进入相应页面，此时页面正常显示，若再次刷新页面则出错。

**Comment by happypeter** [comment]
http://www.staticapps.org/articles/routing-urls-in-static-apps

server 端也要做一些设置的。

或者用 pushstate-sever 就像这个例子一样：https://github.com/rackt/react-boilerplate

**Comment by happypeter** [comment]
备份到 wiki 了。
