### ISSUE TITLE
facebook: relay

### ISSUE THREAD

**Issue by billie66** [happypeter/react-meteor-book#8]
> Facebook just open sourced Relay, an elegant way to integrate data into your React apps! 

https://facebook.github.io/relay/

**Comment by billie66** [comment]
fb relay 员工总结的非官方 relay Q&A

https://gist.github.com/wincent/598fa75e22bdfa44cf47

**Comment by billie66** [comment]
https://www.devcasts.io/p/about-reacts-new-tools-graphql-and-relay/

总结很有意思

**Comment by billie66** [comment]
http://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html

**Comment by billie66** [comment]
https://speakerdeck.com/laneyk/mutations-in-relay

https://speakerd.s3.amazonaws.com/presentations/344776e9d23e4b149d81a63735398412/PDF_with_notes.pdf

**Comment by billie66** [comment]
http://facebook.github.io/graphql/

**Comment by billie66** [comment]
https://www.reindex.io/blog/how-facebooks-graphql-will-change-backend-development/

**Comment by happypeter** [comment]
太难，暂时不用，连 Pete Hunt 都不用
