### ISSUE TITLE
inline styles

### ISSUE THREAD

**Issue by billie66** [happypeter/react-meteor-book#9]
react inline styles

https://facebook.github.io/react/tips/inline-styles.html

https://css-tricks.com/the-debate-around-do-we-even-need-css-anymore/

**Comment by billie66** [comment]
http://hugogiraudel.com/2015/06/18/styling-react-components-in-sass/

**Comment by billie66** [comment]
https://speakerdeck.com/vjeux/react-css-in-js

**Comment by billie66** [comment]
https://medium.com/@jviereck/modularise-css-the-react-way-1e817b317b04

**Comment by happypeter** [comment]
> https://medium.com/@jviereck/modularise-css-the-react-way-1e817b317b04

大家都在争论不休，所以我还是用我的 sass 老方式，静观水落石出。

**Comment by happypeter** [comment]
so inline styling bye , for now at least .
